"""Migration initiation

Revision ID: 811b8cc34982
Revises: 7aeca445e9d2
Create Date: 2022-07-28 21:40:34.846340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811b8cc34982'
down_revision = '7aeca445e9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('address', sa.String(length=20), nullable=True))
    op.alter_column('messages', 'phone',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'phone',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.drop_column('messages', 'address')
    # ### end Alembic commands ###
